var words = ["45 Silenced",
"50cal Sniper",
"A.I.M",
"A.X.E.",
"Abominable Axe",
"Absolute Zero",
"Abstract spray",
"Abstrakt",
"AC/DC",
"Accolades",
"Ace",
"Aerial Assault One",
"Aerial Assault Trooper",
"Aerial Threat",
"Aerobic Assasin",
"Aerobic Assassin",
"Aerosol Assassins loading screen",
"Ahoy! Music",
"Air Horn",
"Air Tank",
"Airflow",
"Airfoil",
"Airheart",
"Airlift",
"Alarm Emoticon",
"AlexRamiGaming",
"Ali-A",
"All-Star",
"All-Star' skydiving trails'",
"Alpine Accessories",
"Alpine Accessories (CAN)",
"Alpine Accessories (CHN)",
"Alpine Accessories (FRA)",
"Alpine Accessories (GBR)",
"Alpine Accessories (GER)",
"Alpine Accessories (KOR)",
"Alpine Accessories (USA)",
"Alpine Ace",
"Alpine Ace (CAN)",
"Alpine Ace (CHN)",
"Alpine Ace (FRA)",
"Alpine Ace (GBR)",
"Alpine Ace (GER)",
"Alpine Ace (KOR)",
"Alpine Ace (USA)",
"Altitude",
"Amazed Emoticon",
"Anarchy Axe",
"Ancient Mask Emoticon",
"Angry Volcano Icon",
"Arachne",
"Arachnids Loading Screen",
"Arcanum",
"Archetype",
"Arctic Assasin",
"Arctic Assassin",
"Arctic Camo Wrap",
"Ark",
"Armadillo",
"Armature",
"Arrow banner icon",
"Arrow spray",
"Assault Trooper",
"Astro",
"Astro' back bling",
"Aurora",
"Autocleave",
"Avxry",
"Awww' emoticon",
"Axcordion",
"Axecalibur",
"Axercise",
"Axeroni",
"Baby Seal emoticon",
"Back Plate",
"Backbone",
"Backstroke",
"Backup Plan",
"Bad Apple Emoticon",
"Bag of Coal Spray",
"Baited Spray",
"Baller",
"Ballistic",
"Ballistics Contrail",
"Balloon Axe",
"Balloon Llama",
"Baloon Axe",
"Bamboo",
"Bananas emoticon",
"Bananas Spray",
"Bandolier",
"Bandolier Loading Screen",
"Bang! Emoticon",
"Basketball Toy",
"Bat Attitude",
"Bat Icon",
"Bats! Contrail",
"Batsickle",
"Battle Axe",
"Battle Balloon",
"Battle Call",
"Battle Hound",
"Battle Royale",
"Battle Shroud",
"Battlehawk",
"BazzaGazza",
"BCC Trolling",
"Beach Ball Toy",
"Beach Umbrella",
"Bear Force One",
"Bee' banner icon",
"Beef Boss",
"Behold!",
"Best Mates",
"Best Mates' emote",
"Bin Banner Icon",
"Bird banner icon",
"Birdshot",
"Birthday Cake",
"Bitemark",
"Black Cat Emoticon",
"Black Knight",
"Black Shield",
"Blackheart",
"Blackheart outfit",
"Bladed Wings",
"Blasting Cap",
"Blaze",
"Blitz",
"Blue Shift",
"Blue Squire",
"Blue Streak",
"Blue Striker",
"Blue Team Leader",
"Bobbin'",
"Bogey Bag",
"Bolt Pistol",
"Bolt Rifle",
"BoltRevolver",
"Bombastic",
"Boneless",
"Bonesy",
"Bonesy Pet",
"Boogie Down",
"Boogie Spray",
"Boombox",
"Boombox' emoticon",
"Bootstraps",
"Booty Buoy Glider",
"Bottom Feeder",
"Bouncy Ball Toy",
"Bow banner icon",
"Brainiac",
"Brat Catcher",
"Brawler",
"Breakdown",
"Breakdown Emote",
"Breakin'",
"Breaking Point",
"Brilliant Striker",
"Bring It",
"Brite Bag",
"Brite Bomber",
"Brite Bomber Spray",
"Brite Gunner",
"Brite Gunner loading screen",
"Brite Unicorn' loading screen",
"Brush Your Shoulders",
"Bubbles",
"Bubbles' skydiving trails",
"Buckled",
"Buckler",
"Bug Icon",
"Bullseye",
"Bunny Brawler",
"Bunnymoon",
"Burgle Bag",
"Burnout",
"Bush' emoticon",
"Busy",
"Cabbie",
"Cactus Maze Spray",
"Calamity",
"Calamity Spray",
"Calavera",
"Calculated",
"Caliper",
"Camo Pet",
"Camper Emoticon",
"Campfire Icon",
"Candy Axe",
"Capoeira",
"Carbide",
"Carbide loading screen",
"Carbon",
"Carbon and Gold Wrap",
"Carbon' glider",
"Care Package",
"Carrot Stick",
"Carver",
"Carver",
"Cash Flow",
"Castor",
"Cat Flip",
"Cat's Claw",
"Catalyst",
"CDNThe3rd",
"Ceeday",
"Celebrate emoticon",
"Chain Banner Icon",
"Chalk Outline spray",
"Checker",
"Cheer Up",
"Chef's Choice",
"Chequered Flag Banner Icon",
"Chick' banner icon",
"Chicken",
"Chicken emoticon",
"Chill-Axe",
"Chomp Jr.",
"Chomp Sr.",
"Chompmasters Loading Screen",
"Chopper",
"Chromium",
"Cipher",
"Circle spray",
"Circuit Breaker",
"Cizzorz",
"Clean Cut",
"Clean Groove",
"Click!",
"Cliffhanger",
"Clinical Crosser",
"Cloaked Shadow",
"Cloaked Star",
"Clockworks",
"Close Shave",
"Cloud Strike",
"Cloudbreaker",
"Clovers Contrail",
"Clown Emoticon",
"Cluefinder",
"Clutch Axe",
"Coaxial Copter",
"Cobalt",
"Cobra Back Bling",
"Cobra Banner Icon",
"Coconuts Icon",
"Codename E.L.F",
"Codename E.L.F.",
"Cold Front",
"Cold Snap",
"Combat Wreath",
"Combo XP boost",
"Commando",
"common",
"Confidential Case",
"Confused",
"Conga emote",
"Conquest",
"Conquest Glider",
"Contagion",
"Controller",
"Cookie Cutter",
"Coral Cruiser",
"Coven Cape",
"Covered Crusader",
"Covered Crusader Glider",
"Cozy Coaster",
"Crab' banner icon",
"Crabby emoticon",
"Crackabella",
"Crackdown",
"Crackshot",
"Crackshot Loading Screen",
"Crafted Carrier",
"Crayator",
"Crazy Feet",
"Creative",
"Crested Cape",
"Crimson Axe",
"Crimson Scout",
"Criss Cross",
"Criterion",
"Crossfire",
"Crowbar",
"Cruiser",
"Cruiser Glider",
"Crusader",
"Crypt Cruiser",
"Crystal Carriage",
"Cuddle Bow",
"Cuddle Team Hula Spray",
"Cuddle Team Leader",
"Cuddly Emoticon",
"Cuff Case",
"Cutting Edge",
"Cyclone",
"Dab",
"dakotaz",
"Dance Moves",
"Dance Therapy",
"DanTDM",
"Dante",
"Dark Bag",
"Dark Bomber",
"Dark Engine",
"Dark Glyph",
"Dark Llama Loading Screen",
"Dark Matter",
"Dark Matter' back bling",
"Dark Shard",
"Dark Vanguard",
"Dark Void",
"Dark Voyager",
"Dark Voyager' outfit",
"Dark Wings",
"Dazzle",
"Deadfire",
"Death Stalker",
"Death Valley",
"Deep Fried",
"Deep Space Lander",
"Deflector",
"Denied",
"Desperado",
"Destabilizer",
"Dev Test Asset",
"Devastator",
"Dice Icon",
"Diecast",
"Dinosaur Skull' banner icon",
"Dip",
"Dire",
"Dire Loading Screen",
"Dire Outfit",
"Dire Spray",
"Director's Cut",
"Dirigible",
"Disco Brawl",
"Disco Diva",
"Disco Fever",
"Discovery",
"Dismal Cape",
"Diverge",
"Divine Dragon",
"Diving Tank",
"DJ Bop",
"DJ Yonder",
"DJ Yonder Loading Screen",
"DJ Yonder Spray",
"Do it! spray",
"Dodger",
"Dodger Pet",
"Dog Bowl banner icon",
"Dog collar' banner icon",
"Dolphin Banner Icon",
"Dominator",
"Double D",
"Double Helix",
"Downshift",
"Dragon Axe",
"Dragon Launcher",
"Dragon Scales Wrap",
"Dragon Sniper",
"DragonGun",
"Dreamflower",
"Drift",
"Drift Spray",
"Driftwood Wrap",
"DrLupo",
"Drop The Bass",
"Drumbeat",
"Dual 45",
"Dual 45 Pick Up",
"Duck banner icon",
"Duo Umbrella",
"Durr Burger Emoticon",
"Durrr Burger Wrap",
"Durrr Spray",
"Dusk",
"Dusk Loading Screen",
"Dusk Outfit",
"Dusk Wings",
"Dusk Wings Back Bling",
"Dusty Depot Loading Screen",
"Dynamic Dribbler",
"Dynamite emoticon",
"Dynamo",
"E.L.I.M.",
"Eagle",
"Eerie Music",
"Egg' banner icon",
"Eggshell",
"Electro Shuffle",
"Electro Swing",
"Elite Agent",
"Elite Agent' loading screen",
"Elite Agent' outfit",
"Elite Cleat",
"Elmira",
"Embarrassed Emoticon",
"Ember",
"Ember Outfit",
"Ember Spray",
"Embers",
"Emoticons! Loading Screen",
"Empire Axe",
"End Zone",
"Enduring Cape",
"Enforcer",
"Eon",
"Epic",
"Epic Games",
"Equalizer",
"Equilibrium",
"EVA",
"Evidence Bag",
"Evil Eye",
"Exhaust Contrail",
"F Emoticon",
"Fable",
"Fable Outfit",
"Fabled Cape",
"Face Palm",
"Fake Door Spray",
"Fallen Love Ranger",
"Fallen Love Ranger Spray",
"Fancy Basketball",
"Fancy Beach Ball Toy",
"Fancy Burger Toy",
"Fancy Feet",
"Fancy Golf Ball Toy",
"Fancy Tomato Toy",
"Far Out Man",
"Fate",
"Fate Loading Screen",
"Fated Frame",
"FaZe Cloak",
"FaZe Rug",
"FaZe Tfue",
"Fe4RLess",
"Feathered Flyer",
"Fence banner icon",
"Festive Music",
"Festive Paper Wrap",
"Fiber Optics Contrail",
"Field Surgeon",
"Field Wraith",
"Fighter Kite",
"Filet Axe",
"Film camera banner icon",
"Finesse Finisher",
"Finger Guns",
"Finger Wag",
"FireCrackerGun",
"Fireflies Contrail",
"Firewalker",
"Fireworks Team Leader",
"First Downer",
"First strike Specialist",
"Fish Tank",
"Fishstick",
"Fist Pump",
"Flamenco",
"Flamenco Emote",
"Flames",
"Flames' skydiving trails",
"Flaming Rage' emoticon",
"Flapjackie",
"Flapper",
"Flappy",
"Flappy Flyer",
"Flatliner",
"Flinlock Sniper Hightier",
"FlinLock Sniper LowTier",
"Flintlock Launcher",
"Flintlock Revolver",
"Flippin' Incredible",
"Flippin' Sexy",
"Floss",
"Flurry",
"Flutterbug",
"Flux",
"Fly Icon",
"Flying Carp",
"Flying Fish",
"Flying Saucer",
"Flytrap",
"Flytrap Loading Screen",
"Forebearer",
"Forerunner",
"Fortnite",
"Fortune",
"Fossil Flyer",
"Founder's Glider",
"Founder's Umbrella",
"Four-Leaf Clover Emoticon",
"Free Flow",
"Free Flow Emote",
"Freestylin'",
"Fresh",
"Frostbite",
"Frostwing",
"Frozen Axe",
"Frozen Iron Cage",
"Frozen Love Ranger",
"Frozen Love Wings",
"Frozen Raven",
"Frozen Red Knight",
"Frozen Red Shield",
"Frozen Shroud",
"Funk Ops",
"Fyra",
"Galactic Disc",
"Galaxy",
"Gale Force",
"Gale Force pickaxe",
"Garrison",
"Gatekeeper",
"Gemstone Wrap",
"Gentleman's Dab",
"Get Down!",
"Get Funky",
"Get Funky Emote",
"GG Potion Emoticon",
"GG Smiley spray",
"GG Wreath Emoticon",
"Ghost Emoticon",
"Ghost Icon",
"Ghost Portal",
"Ghoul Trooper",
"Giddy Gunner",
"Giddy-up",
"Giddy-Up Outfit",
"Ginger Gunner",
"Ginger Gunner Emoticon",
"Gingerbread Loading Screen",
"Gingersled",
"Glider",
"Glidurrr",
"Glimmer",
"Glitch in the System",
"Glitter-up",
"Global Axe",
"Glow Rider",
"Glow Stick",
"Glowsticks",
"Glyphs Contrail",
"Go Emoticon",
"Go! Go! Go!",
"Goalbound",
"Golden Pigskin",
"Golf Ball Banner Icon",
"Golf Ball Toy",
"Golf Clap",
"Golf Clap Emote",
"Good Vibes Spray",
"Goodie Bag",
"Goodie Bag back bling",
"Goodie Gourd",
"Googly",
"Gremlins Spray",
"Grenade banner icon",
"Gridiron",
"Grill Sergeant",
"Grimbles",
"Groove Jam",
"Groove Jam emote",
"Ground Pound",
"Growler",
"Grumpy Tree Spray",
"Guan Yu",
"Guandao",
"Guiding Glow",
"Gum Drop",
"Gumshoe",
"Gun Show",
"Gurney Gear",
"Hacivat",
"Half Shell",
"Hallowhead",
"Hamirez",
"Hamirez Brown Style",
"Hamirez Pink Style",
"Hamlinz",
"Hand Signals",
"Hang Time",
"Happy Whale' banner icon",
"Hard Boiled",
"Harpoon Axe",
"Harvester",
"Harvesting Tools' loading screen",
"Hat Banner Icon",
"Hatchback",
"Hatchling",
"Havoc",
"Hawk' banner icon",
"Hay Man",
"Haywire",
"Hazard Agent",
"Headbanger",
"Heartbroken' emoticon",
"Hearts",
"Hearts skydiving trails",
"Hearts spray",
"Heidi",
"Helium",
"Hello Friend emote",
"Herald's Wand",
"Herald's Wand",
"High Octane",
"Highland Warrior",
"Highrise Assault Trooper",
"Hime",
"Hip Shakers",
"Hitchhiker",
"Hoarder' emoticon",
"Hollowhead",
"Honor Guard",
"Hoop Master emote",
"Hootenanny",
"Hot Dog' emoticon",
"Hot Marat",
"Hot Ride",
"Hot Rod",
"Hot Stuff",
"Howl",
"Hula",
"Hunting Rifle 01",
"Huntress",
"Huntress Loading Screen",
"Hybrid",
"Hydraulic Launcher",
"Hydraulic Style Pistol",
"Hydraulic Style Sniper Rifle",
"Hype",
"Hype emote",
"Hyper",
"Hyperion",
"I AM WILDCAT",
"Ice Breaker",
"Ice Cream Truck Banner Icon",
"Ice Crystals",
"Ice Crystals Contrail",
"Ice Cube",
"Ice Cube Back Bling",
"Ice Mantle",
"Ice Puck Toy",
"Ice Scepter",
"Icebringer",
"Icicle",
"IDK",
"Ignition",
"Indigo Ice Wrap",
"Infiltrator",
"Infinite Dab",
"Insight",
"Insignia",
"Instigator",
"Instinct",
"Intensity",
"Interceptor",
"Intrepid",
"Intrepid glider",
"Introllsive",
"Inverted Blade",
"Iron Beak",
"Iron Cage",
"Isle of Treasure Loading Screen",
"It&apos;s Go Time!",
"iTemp Plays",
"Jack Gourdon",
"Jackalope",
"Jacksepticeye",
"Jackspammer",
"Jaeger",
"Jailbirds Loading Screen",
"Jawblade",
"Jellyfish Icon",
"Jingu Bang",
"Job Well Done",
"Jolly Roger",
"Jubilation",
"Jugglin'",
"Juke",
"Jumpshot",
"Jungle Scout",
"Junkjet",
"Kaboom' emoticon",
"Kabuto",
"Keytar",
"Kick Drum",
"Kick Ups",
"Kiss Kiss",
"Kiss spray",
"Kitbash",
"Knee Slapper",
"Krampus",
"Krampus' Little Helper",
"Krampus&apos; Little Helper",
"Lace",
"Lachlan",
"Lamp",
"Lamplight",
"Lane Splitter",
"Lanterns",
"Lanterns Contrail",
"Laser Chomp",
"Last Gasp",
"Laugh It Up",
"Laval Contrail",
"LazarBeam",
"Lazy Shuffle",
"Lead Swinger",
"Leviathan",
"Leviathan loading screen",
"Libre",
"Lightning",
"Lightning banner icon",
"Lightning Icon",
"Lightning skydiving trails",
"Lightning' banner icon",
"Lil Whip",
"Lil&apos; Kev",
"Liteshow",
"Living Large",
"Llama Bell",
"Llama De Muertos Spray",
"Llama Icon",
"Llamacadabra",
"Lockpick Tool",
"Lockstep Glider",
"Lollipopper",
"Long Legs",
"Longhorn",
"Longshot",
"Looted spray",
"Loserfruit",
"Love Ranger",
"Love Ranger Spray",
"Love Wings",
"Loyal Shield",
"LSK",
"Lucha GG Spray",
"Lucky",
"Ludwig",
"Lug Axe",
"Luxe",
"Luxe Outfit",
"Luxe Spray",
"Lynx",
"Lynx Spray",
"Mace' banner icon",
"Machine Pistol",
"MachineGun 01",
"MachineGun Halloween",
"Magic Wings",
"Magnifying Axe",
"Magnus",
"Mainframe",
"Majestic' emoticon",
"Make it Rain",
"Maki Master",
"Mako",
"Malcore",
"Mangnum",
"Manhole Cover Spray",
"Marsh Walk",
"Marshmello",
"Mask Banner Icon",
"Mask spray",
"Masked  Fury",
"Masked Fury",
"Master Key",
"Master Key Loading Screen",
"Master Key Outfit",
"Maven",
"Maverick",
"Maximilian",
"Maximillian",
"Mayhem",
"Meat Banner Icon",
"Meeet Emoticon",
"Mello Rider",
"Meltdown",
"Meow Moon Spray",
"Mermaid Fin Icon",
"Mermaid Spray",
"Merry Marauder",
"Merry Marauder Banner Icon",
"Mertank",
"Mic Drop",
"Midfield Maestro",
"Midnight Ops",
"MilitarySMG Silenced",
"Millitary M202 Launcher",
"Mime Time",
"Mind Blown",
"Mini Marauder",
"Minigun' loading screen",
"Mission Specialist",
"Mistletoe Emoticon",
"Mittens Emoticon",
"MM7Games",
"Modern",
"Mogul Master",
"Mogul Master (CAN)",
"Mogul Master (CHN)",
"Mogul Master (FRA)",
"Mogul Master (GBR)",
"Mogul Master (GER)",
"Mogul Master (KOR)",
"Mogul Master (USA)",
"Mogul Ski Bag",
"Mogul Ski Bag (CAN)",
"Mogul Ski Bag (CHN)",
"Mogul Ski Bag (FRA)",
"Mogul Ski Bag (GBR)",
"Mogul Ski Bag (GER)",
"Mogul Ski Bag (KOR)",
"Mogul Ski Bag (USA)",
"Moisty Merman",
"Moniker",
"Monsoon",
"Moon and Clouds' banner icon",
"Moonrise",
"Moonwalker",
"Moonwalker' outfit",
"Morgz",
"Moth Spray",
"Mother Coconuts",
"Mothmando",
"Mouldering Cloak",
"Mouse Icon",
"Mullet Marauder",
"Mullet Marrauder",
"Munitions Expert",
"Muselk",
"Musha",
"My Idol!",
"Nana Nana emote",
"Nara",
"Naughts and Crosses Banner Icon",
"Neon Cat Spray",
"Neon Glow Launcher",
"Neon Glow Pistol",
"Neon Sniper",
"Nibbles",
"Night Cloak",
"Night Cloak Back Bling",
"Night Slicer",
"Nightshade",
"Nightshade Outfit",
"Ninja",
"Ninja Star Banner Icon",
"Nite Nite",
"Nite Owl",
"Nitelite",
"NoahJAFK",
"NoahsNoah",
"Nog Ops",
"Noir",
"Norse Emblem Loading Screen",
"Norse Llama Spray",
"Number 1' emoticon",
"Oblivion",
"Octo-Pirate Emoticon",
"Octopus Banner Icon",
"Offworld Rig",
"OG",
"Oktoberfeast",
"Omega",
"Omega outfit",
"Omen",
"Omen Loading Screen",
"Ominous Orb",
"On the Hook",
"Onesie",
"Onesie Outfit",
"Oni Spray",
"Onslaught",
"Oracle Axe",
"Orange Justice",
"Orbital Shuttle",
"Outburst",
"Overtaker",
"P.A.N.D.A Team Leader",
"Palm Tree Emoticon",
"Palm Trees Banner Icon",
"Paper Parasol",
"Paper Plane",
"Paradigm",
"Paradox",
"Party Animal",
"Pastel Patrol Loading Screen",
"Patch Patroller",
"Pathfinder",
"Pathogen",
"Patterned Icon",
"Patty Whacker",
"Paw' banner icon",
"Peekaboo",
"Peeled Spray",
"Peely",
"Peely Outfit",
"Pencil banner icon",
"Penguin",
"Penguin Emoticon",
"Perfect Present",
"Perfect Present Back Bling",
"Permafrost",
"Persuader",
"Petunia",
"PewDiePie",
"Phntasm Contrail",
"Phone It In",
"Pick Squeak",
"Pickaxe",
"Pickaxe Icon",
"Picnic",
"Picnic Glider",
"Pigskin",
"Piledriver",
"Pinapple Icon",
"Pink Flamingo",
"Pinpoint",
"Pistol 02",
"Pistol Auto",
"Pistol HandCannon BR",
"Pivot",
"Pixel Ramirez Spray",
"Pixel Raven Spray",
"Plague",
"Planetary Probe",
"Plotting emoticon",
"Plunger Emoticon",
"Plunja",
"Point It Out",
"Pointer",
"Poised Playmaker",
"Pokimane",
"Poofy Parasail",
"Pool Party",
"Pool Party Emoticon",
"Pop Lock",
"Popcorn",
"Popcorn emote",
"PopularMMOs",
"Porthole Spray",
"Positron",
"Post Apocalyptic Launcher",
"Post Apocalyptic Pistol",
"Post Apocalyptic Sniper",
"Pot O' Gold",
"Pot of Gold Emoticon",
"Potato Aim Spray",
"Powder",
"Powder Outfit",
"Power Chord",
"Power Chord Loading Screen",
"Power Grip",
"Praise The Tomato",
"Precision",
"Pretzel Protector",
"Prickly Emoticon",
"Prismatic",
"Prodigy",
"Propeller Axe",
"Pterodactyl",
"Pulse Axe",
"Pumpernickel",
"PumpkinLauncher",
"Puncture Pack",
"Pure Salt",
"Purrfect",
"Purrfect.",
"Pursuit",
"Pyramid Icon",
"Rabbit Raider",
"Rabid emoticon",
"Radiant Striker",
"Ragnarok",
"Ragnarok Outfit",
"Raider's Revenge",
"Rain Cloud' banner icon",
"Rainbow",
"Rainbow Glider",
"Rainbow Glider Elite",
"Rainbow Rider",
"Rainbow Rider' glider",
"Rainbow Smash",
"Rainbow spray",
"Rainbow' skydiving trails",
"Ralphs Revenge",
"Rambunctious",
"Random Glider",
"Ranger",
"Rapscallion",
"Raptor",
"Raptor Satchel",
"Raptor' loading screen",
"Rare",
"Rat Rod Machine Pistol",
"Ravage",
"Ravage Loading Screen",
"Raven",
"Raven loading screen",
"Raven spray",
"Rawr",
"Raygun Pistol",
"RayGunAuto 01",
"Razor Edge",
"RC Rocket Export",
"Reaction Tank",
"Reanimated",
"Reaper",
"Rearguard",
"Rearguard Back Bling",
"Rebel",
"Reckoning",
"Recon Expert",
"Recon Scout",
"Recon Specialist",
"Recruit - Banshee",
"Recruit - Hawk",
"Recruit - Headhunter",
"Recruit - Jonesy",
"Recruit - Ramirez",
"Recruit - Renegade",
"Recruit - Spitfire",
"Recruit - Wildcat",
"Red Card",
"Red Knight",
"Red Knight Loading Screen",
"Red Shield",
"Red-Nosed Raider",
"Red-nosed Ranger",
"Redline",
"Redline Outfit",
"Reef Ranger",
"Reflex",
"Regal Wave",
"Remus Ice Style",
"Remus Pet",
"Remus Skull Style",
"Renegade",
"Renegade Raider",
"Renegade Roller",
"Rescue Paddle",
"Rescue Ring",
"Resonator",
"Respect",
"Response Unit",
"Retro Sci-fi",
"Retro Sci-fi Skydiving Trails",
"Revolt",
"Rex",
"Rex loading screen",
"Rhinestone Rider",
"Rickety Runner",
"Rickety Runner Glider",
"Ride the Pony",
"Rift Edge",
"Riot",
"RNGmrfreshasian",
"RNGx2Twins",
"Road Flair",
"Road Ready",
"Roadtrip",
"Rock Out",
"Rock Paper Scissors",
"Rocket Ride' emoticon",
"Rocket Rodeo",
"Rocket Spinner",
"Rogue Agent",
"Rook",
"Rook Outfit",
"Rosa",
"Rose Team Leader",
"Rotor",
"Royal Stroll spray",
"Royale Air",
"Royale Bomber",
"Royale Dragon",
"Royale Flags",
"Royale Knight",
"Royale Shield",
"Royale X",
"RPG7",
"Ruckus",
"Runic",
"Runic Contrail",
"Running Man",
"Running Man Emote",
"Rush",
"Rust Bucket",
"Rust Lord",
"Rust Lord' outfit",
"Rusty Rider",
"Safecracker",
"Salty Spray",
"Salute",
"Sanctum",
"Sash Sergeant",
"Sashimono",
"Save the World",
"Sawtooth",
"Sawtooth' harvesting tool",
"Scales",
"Scales Pet",
"Scaly",
"SCAR Rameriez",
"Scarlet Defender",
"Scope Satchel",
"Scorcher",
"Scorecard",
"Scorpion",
"Scoundrel",
"Scourge",
"Scout",
"Scrambler",
"Scratchmark",
"Servo",
"Sgt. Green Clover",
"Sgt. Green Clover Loading Screen",
"Sgt. Winter",
"Sgt. Winter Outfit",
"Shackled Stone",
"Shade",
"Shadow Ops",
"Shadow Ops spray",
"Shadow Puppet",
"Shadow Wings",
"Shake It Up",
"Shaolin Sit-up",
"Shark Fin",
"Shimmer",
"Shimmer Emote",
"Shiro",
"Shogun",
"Shooting Star",
"Shooting Star skydiving trails",
"Shopping Trolley Banner Icon",
"Shotgun 04 Heavy",
"Shotgun Military",
"Showstopper",
"Shredder",
"Shrimpy",
"Sidewinder",
"Sidewinder Outfit",
"Sight Sling",
"Signal Hub",
"Silver Fang",
"Sir Glider the Brave",
"Six String",
"Six String Striker",
"SixShooter",
"Skeleton Key Spray",
"Ski Boot",
"Skirmish",
"Skull and Beard Spray",
"Skull Icon",
"Skull Ranger",
"Skull Sickle",
"Skull Squad Loading Screen",
"Skull Trooper",
"Skully",
"Skully Emoticon",
"Sky Serpents Glider",
"Sky Stalker",
"Slam Dunk",
"Slashed",
"Sledgehammer",
"Sledgehammer Outfit",
"Sleuth",
"Slick",
"Slipstream",
"Slitherin' Emote",
"Slitherin&apos;",
"Slow Clap",
"Slushy Jr.",
"Slushy Soldier",
"Smash Up",
"Smash Up Harvesting Tool",
"Smooth Moves",
"Smooth Ride",
"Snake' banner icon",
"Snap",
"Sniper 01",
"Sniper 02",
"Sniper Bolt Action",
"Sniper Exterminator",
"Snoozefest emote",
"Snorkel Banner Icon",
"Snorkel Ops",
"Snow Globe",
"Snow Squall",
"Snowblades",
"Snowfall",
"Snowflake",
"Snowfoot",
"Snowstrike",
"Solid Strider",
"Something Stinks",
"Space Pistol",
"Sparkle Specialist",
"Sparkler",
"Sparkplug",
"Special Delivery",
"Special Forces",
"Spectral Axe",
"Spectral Essence Contrail",
"Spectre",
"Spellbinder",
"Spellslinger",
"Spicy Emoticon",
"Spider Banner Icon",
"Spider Knight",
"Spider Shield",
"Spike",
"Spike Chamber",
"Spike It",
"Spiky",
"Spirit",
"Spirit Cape",
"Splashdown",
"Splashdown Glider",
"Splinterstrike",
"Split Wing",
"Spooky Team Leader",
"Spots Icon",
"Spray Collage Loading Screen",
"Spray Paint",
"Spray Paint skydiving trails",
"Spraypaint banner icon",
"Sprinkler",
"Squad Leader",
"Squad Leader loading screen",
"Squad Leader outfit",
"Squad Umbrella",
"Squat Kick",
"Squeaky Clean Music",
"Squire Shield",
"SSSniperWolf",
"SSundee",
"Stabilizer",
"Stage Dive",
"Stage Slayer",
"Stalwart Sweeper",
"Standard Issue",
"Star Power",
"Star Power Music",
"Star-Spangled Ranger",
"Star-Spangled Trooper",
"Starry Flight",
"Steadfast",
"Stealth",
"Steelcast",
"Steelsight",
"Stellar Axe",
"Step it Up",
"Stinky Emoticon",
"Stop Axe",
"Stop Emoticon",
"Storm Salutation",
"Storm Sigil",
"Straberry Paws Spray",
"Straw Ops",
"String Lights Contrail",
"Striped Soldier",
"Strong Guard",
"Strongbox",
"Studded Axe",
"Sub Commander",
"Subjugator",
"Sugar Crash",
"Sugar Crash glider",
"Sugarplum",
"Summer Strummer",
"Summit Striker",
"Sun Banner Icon",
"Sun Strider",
"Sun Strider Loading Screen",
"Sun Strider Outfit",
"Sun Tan Specialist",
"Sun' banner icon",
"Sunprint Wrap",
"Super Striker",
"Support Squadron Loading Screen",
"Supressed Pistol' loading screen",
"Survival Specialist",
"Survivial Specialist",
"Sushi Master",
"Sushi Spray",
"Swag Bag",
"Swarm",
"Swarm Glider",
"Swipe It",
"Swipe It Emote",
"Swirls Contrail",
"Synth Star",
"SypherPK",
"T-Pose",
"T-Square",
"Tabulator",
"Tactical Shotgun' loading screen",
"Tactical Sleigh",
"Tactical Sleigh Glider",
"Tactical Spade",
"Tactics Officer",
"Tag Bag",
"Tai Chi",
"Take 14",
"Take The Elf",
"Take the L",
"Take The L' emote",
"Taro",
"Tartan Banner Icon",
"Tasty Emoticon",
"Tat Axe",
"Tattered Emoticon",
"TBD",
"TBNRfrags",
"Tech Ops",
"Techie",
"Teddy Bear' banner icon",
"Teknique",
"Teknique outfit",
"Teknique spray",
"Telemetry",
"Tender Defender",
"Tender Defender Loading Screen",
"Tenderizer",
"Tendril",
"Terminus",
"The Ace",
"The Brood Spray",
"The Ice King",
"The Ice King Outift",
"The Ice Queen",
"The Ice Queen Loading Screen",
"The Reaper",
"The Reaper (John Wick)",
"The Reaper' outfit",
"The Rebot' emote",
"The Robot",
"The Umbrella",
"The Visitor",
"The Worm",
"Thief' emoticon",
"Three Llamas spray",
"Throttle",
"Thumbs Down",
"Thumbs Down' emoticon",
"Thumbs Up",
"Thumbs Up' emoticon",
"Thunder Crash",
"Tidy",
"Tie-dye Flyer",
"Tiger Stripes Icon",
"Time Out",
"TimTheTatman",
"Tinseltoes",
"ToiletPaper",
"Tomato Head",
"Tomato Temple Loading Screen",
"Tomato Toy",
"Tomatohead",
"Tomatohead Loading Screen",
"Tome Pouch",
"Tooth Pick",
"Top Hat' banner icon",
"Top Notch",
"Touchdown",
"Tower Recon Specialist",
"Toxic Trooper",
"TP Contrail",
"Tracker",
"Trail Tote",
"Trail Tote Back Bling",
"Trailblazer",
"Trap Warning spray",
"Treat Yourself",
"Tree Splitter",
"Triage Trooper",
"Triangle banner icon",
"Tricera Ops",
"Tricera Ops Loading Screen",
"Triple Threat",
"Triumph",
"Trog",
"Trog Drawings Spray",
"Trog Outfit",
"Trooper",
"Tropical Camo Wrap",
"True Heart",
"True Love",
"True North",
"Trusty No. 2",
"Trusty No. 2' harvesting tool",
"Trusty Tusks",
"TSM_Daequan",
"TSM_Myth",
"Tunnel spray",
"Turbine",
"Tusk",
"Twist",
"Twist Music",
"Typical Gamer",
"Ultra Red Wrap",
"Ultramarine",
"Ultramarine' skydiving trails",
"Uni-horn",
"Unwrapped",
"Uplink",
"Upright Axe",
"Valkyrie",
"Valkyrie Loading Screen",
"Valkyrie Wings",
"Valor",
"Valor outfit",
"Ventura",
"Ventura Cape",
"Venturion",
"Venturion Cape",
"Venus Flyer",
"Verge",
"Vertex",
"Viceroy Mark I",
"Victory Lap",
"Vigilante",
"Vikkstar123",
"VinderTech MachinePistol",
"VinderTech Revolve",
"VinderTech Sniper",
"Vintage",
"Virtue",
"Vision",
"Vivacious",
"Volley Girl",
"Voyager",
"VT Laucher",
"VT Revolver",
"VT Sniper",
"VTPistol",
"Vuvuzela",
"Wallcrawler Spray",
"Warpaint",
"Warthog",
"Wasp",
"Waterworks",
"Wave",
"Waveform",
"Waypoint",
"Web Breaker",
"Webrella",
"Wet Paint",
"Whiplash",
"Whirlwind",
"Whistle Warrior",
"White Fang",
"White Squall",
"Whiteout",
"Wiggle",
"Wild Card",
"Windbreaker",
"Window spray",
"Wing' banner icon",
"Wingback",
"Wingman",
"Wings of Valor",
"Wings of Valor glider",
"Wingtip",
"Wolf' banner icon",
"Wolfpack",
"Woodsy",
"Woodsy Pet",
"Woofs",
"Woot Bonesy Spray",
"Work It Out",
"Worm' banner icon",
"Wow' emoticon",
"Wreath Banner Icon",
"Wreck Raider",
"Wukong",
"Wukong Bundle",
"X Mark spray",
"XpertThief",
"Yee-Haw!",
"You Shouldn't Have!",
"You're Awesome",
"You're Awesome Emote",
"Yuletide Ranger",
"Yummy Spray",
"Zany",
"Zenith",
"Zenith Outfit",
"Zephyr",
"Zig-Zag Icon",
"Zoey",
"Zoey loading screen",
"Zoey outfit",
"ZZZ emoticon"];

window.addEventListener("load", function() {
		var randoms = window.document.getElementsByClassName("randoms");
		for (i = 0; i < randoms.length; i++)
				changeWord(randoms[i]);
}, false);

function changeWord(a) {
		a.style.opacity = '0.1';
		a.innerHTML = words[getRandomInt(0, words.length - 1)];
		setTimeout(function() {
				a.style.opacity = '1';
		}, 425);
		setTimeout(function() {
				changeWord(a);
		}, getRandomInt(1000, 2019));
}


function getRandomInt(min, max) {
		return Math.floor(Math.random() * (max - min + 1)) + min;
}